### ISSUE TITLE
Weird Menu interaction with List

### ISSUE THREAD

**Issue by Fredemus** [vizia/vizia#329]
When a `Menu` has a submenu that's contained in a `List`, its layout seems to break down somewhat. The submenu's entries end up being drawn on top of it, instead of where you'd expect.

[code that reproduces it](https://gist.github.com/Fredemus/de1a0e749c7d26409584598fbc0173e5)

**Comment by geom3trik** [comment]
The issue here is actually a styling one. I've tracked it down to the following in the default stylesheet:
```css
menustack.vertical > menu > menustack {
    left: 100%;
}
```
So the nested menustack of the vertical menu gets the `100%` left if it's a child of a menu that's a child of a vertical menustack. Because the list is the parent of the menu this rule no longer applies. At some point I'll correct this in the default stylesheet, but for now if you add a class to the list then you should be able to do the following in your stylesheet:
```css
.list_class > menu > menustack {
    left: 100%;
}
```

**Comment by Fredemus** [comment]
That works, thank you! Maybe so other people don't run into this issue, the default stylesheet should contain:
```css
list > menu > menustack {
    left: 100%;
}
```
which works without applying a class to the list.
I can make a PR if you want
