### ISSUE TITLE
90 degree rotated label seem to be layed out with its width and height swapped

### ISSUE THREAD

**Issue by Fredemus** [vizia/vizia#392]
[example here.](https://gist.github.com/Fredemus/4bb5c6cdc9873de889262f012601cded)

In that example, the text  in the `Label` should be aligned with the start of the word 10 pixels above the bottom of the black `HStack`, but it clips through even though it's able to fit

Changing the height of the label seems to change its height before it's rotated, which makes sense, but it also changes how it's layed out height-wise but not width-wise - that is I can stop it from clipping by changing its height, but that has weird effects for its centering. Maybe some layout is being applied according to its bounds before it's being rotated, but some isn't?

**Comment by geom3trik** [comment]
I think the behaviour is correct, the bit that's confusing things (I think) is that the transform happens relative to the centre of the label. I think to get what you want you could shift the label (before transform) so that it's left edge is centered (`left: 50%`), and then set the transform origin to the center of the left side (`transform-origin: center left`). Then after rotation it would place the label 10px + half the height of the label from the bottom:

<img width="21" alt="image" src="https://github.com/vizia/vizia/assets/9365407/6f43a5af-a6a6-433e-bf0e-7ef32ceb22e4">

Some tweaking on the `bottom` property might be needed to place it where you want.

The css looks like this (based on your example):
```css
.module-sidebar-title {
  top: 1s;
  width: auto;
  height: 20px;
  overflow: visible;
  bottom: 10px;
  border-width: 1px;
  border-color: red;
  z-index: 200;
  /* child-right: 1s; */
  rotate: -90deg;
  transform-origin: center left;
  left: 50%;
  color: #ffffff;
}
```
