### ISSUE TITLE
css variables in the style sheet

### ISSUE THREAD

**Issue by Fredemus** [vizia/vizia#51]
It would be cool to be able to do something like
```css
:root {
  --main-bg-color: brown;
}
.bode {
  color: var(--main-plot-color);
}
.waveform {
  color: var(--main-plot-color);
}
```
Would make customizing big style sheets a bit easier and would help with adding skins for my synth at some point
